# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  terraform:
    jobs:
      - terraform/init:
          checkout: true
          context: terraform
          resource_class: small
          path: terraform
      - terraform/fmt:
          checkout: true
          context: terraform
          resource_class: small
          persist-workspace: true
          path: terraform
          requires:
            - terraform/init
      - terraform/validate:
          checkout: true
          context: terraform
          resource_class: small
          path: terraform
          persist-workspace: true
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          resource_class: small
          path: terraform
          requires:
            - terraform/validate
